{% set name = "mpl-gui" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpl-gui-{{ version }}.tar.gz
  sha256: b1d69300a5544f463d5a6814ffd0d308eef0a2bd38389aab7d04c4e5095b5dde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base

test:
  imports:
    - mpl_gui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tacaswell/mpl-gui
  summary: Prototype project for splitting pyplot in half
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
